# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-10 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mystore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mystore_base_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mystore_base_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='box',
            name='id',
        ),
        migrations.AlterField(
            model_name='box',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='box',
            name='base_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mystore.Base'),
            preserve_default=False,
        ),
    ]
